name: Build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-x86
            os: ubuntu-latest
            args: CFLAGS=-m32
            deps: sudo apt-get install libc6-dev-i386
          - name: linux-x86_64
            os: ubuntu-latest
            args: CFLAGS=-m64
#           - name: macos-arm64
#             os: macos-latest
#             args: CFLAGS='-arch arm64'
#             deps: sudo xcode-select -switch /Applications/Xcode_12.3.app
          - name: macos-x86_64
            os: macos-latest
            args: CFLAGS='-arch x86_64'
    steps:
      - name: Dependencies
        run: ${{ matrix.deps }}
      - name: Version
        if: ${{ matrix.name == 'macos-arm64' }}
        run: cc --version
      - uses: actions/checkout@v2
      - name: Build
        run: make ${{ matrix.args }} all
      - name: Test
        run: make run
